/**
 * ReportBUpload Component
 * Admin interface for uploading JSON quality check reports
 */

import React, { useState } from 'react';
import { uploadReportB } from '../../services/reportBService';
import './ReportBUpload.css';

const ReportBUpload = ({ bookId, userId, onUploadSuccess }) => {
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState(null);
  const [selectedFile, setSelectedFile] = useState(null);

  const handleFileSelect = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    // Validate file type
    if (!file.name.endsWith('.json')) {
      setError('Please select a JSON file');
      setSelectedFile(null);
      return;
    }

    setSelectedFile(file);
    setError(null);
  };

  const handleUpload = async () => {
    if (!selectedFile) {
      setError('Please select a file first');
      return;
    }

    try {
      setUploading(true);
      setError(null);

      // Read file content
      const fileContent = await readFileAsText(selectedFile);
      
      // Parse JSON
      let reportData;
      try {
        reportData = JSON.parse(fileContent);
      } catch (parseError) {
        throw new Error('Invalid JSON file. Please check the file format.');
      }

      // Validate report structure
      if (!reportData.report_metadata || !reportData.results_by_source_file) {
        throw new Error('Invalid report structure. Missing required fields.');
      }

      // Upload to Firestore
      await uploadReportB(bookId, reportData, selectedFile.name, userId);

      // Success
      setSelectedFile(null);
      if (onUploadSuccess) {
        onUploadSuccess();
      }

      alert('Report uploaded successfully!');

    } catch (err) {
      console.error('Error uploading report:', err);
      setError(err.message || 'Failed to upload report');
    } finally {
      setUploading(false);
    }
  };

  const readFileAsText = (file) => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = (e) => resolve(e.target.result);
      reader.onerror = (e) => reject(new Error('Failed to read file'));
      reader.readAsText(file);
    });
  };

  return (
    <div className="report-b-upload">
      <div className="upload-header">
        <h3>📤 Upload Quality Check Report (JSON)</h3>
        <p>Upload a JSON report file to enable quality review and feedback</p>
      </div>

      <div className="upload-container">
        <div className="file-input-wrapper">
          <input
            type="file"
            accept=".json"
            onChange={handleFileSelect}
            disabled={uploading}
            id="report-file-input"
            className="file-input"
          />
          <label htmlFor="report-file-input" className="file-input-label">
            <span className="file-icon">📁</span>
            <span className="file-label-text">
              {selectedFile ? selectedFile.name : 'Choose JSON file...'}
            </span>
          </label>
        </div>

        {selectedFile && (
          <div className="file-info">
            <span className="file-size">
              {(selectedFile.size / 1024).toFixed(2)} KB
            </span>
          </div>
        )}

        <button
          onClick={handleUpload}
          disabled={!selectedFile || uploading}
          className="btn-upload"
        >
          {uploading ? (
            <>
              <span className="spinner small"></span>
              Uploading...
            </>
          ) : (
            <>
              <span>⬆️</span>
              Upload Report
            </>
          )}
        </button>

        {error && (
          <div className="upload-error">
            <span className="error-icon">⚠️</span>
            <span>{error}</span>
          </div>
        )}
      </div>

      <div className="upload-instructions">
        <h4>📋 Instructions</h4>
        <ul>
          <li>Select a valid JSON report file generated by the quality check pipeline</li>
          <li>The report should contain <code>report_metadata</code> and <code>results_by_source_file</code></li>
          <li>Once uploaded, users can review issues and provide feedback</li>
          <li>Uploading a new report will replace the existing one</li>
        </ul>
      </div>
    </div>
  );
};

export default ReportBUpload;

